disabled_rules:
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - function_parameter_count
  - line_length
  - nesting
  - type_body_length
  - variable_name
  - empty_parentheses_with_trailing_closure

opt_in_rules:
  - vertical_whitespace
  - operator_usage_whitespace
  
type_name:
    min_length: 2

statement_position:
    statement_mode: uncuddled_else

trailing_comma:
    mandatory_comma: true

excluded:
  - Pods
